// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqchntchnyrvxumiross.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxY2hudGNobnlydnh1bWlyb3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzQwMTcsImV4cCI6MjA3Mzg1MDAxN30.56z69uvst76Dlxbga2EAvsfQmj97kKxHFx5o5a4QaOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});